"""
Tests for the CSV-primary validate-intake flow (ADR-0009).

Synthetic fixtures mimic the real EDR profile:
  - exif_data.csv with the same 28-column schema (6 always-null cols included)
  - TIFFs generated by PIL matching ADR-0009 Finding B: Software=Adobe Photoshop,
    no ExposureTime/FNumber/ISO/FocalLength/DateTimeOriginal, Make/Model present.

No real 17 MB EDR TIFFs are committed.  The synthetic TIFFs use 4000×3000 with
a solid fill color; LZW-compressed solid images are a few KB each.
"""

from __future__ import annotations

import csv
import dataclasses
import io
import json
from pathlib import Path
from typing import Any

import pytest
from PIL import Image, TiffImagePlugin

from reef_sfm_provenance.__main__ import build_parser
from reef_sfm_provenance.ids_csv import IdsRecord, load_ids_csv
from reef_sfm_provenance.inventory import ImageRecord, build_inventory
from reef_sfm_provenance.validation import (
    EXPECTED_EXIF_ARTIST,
    EXPECTED_EXIF_COPYRIGHT,
    validate_dataset,
    validate_image,
)

# ---------------------------------------------------------------------------
# EXIF tag IDs
# ---------------------------------------------------------------------------

TAG_MAKE = 271
TAG_MODEL = 272
TAG_ARTIST = 315
TAG_COPYRIGHT = 33432
TAG_SOFTWARE = 305
TAG_ORIENTATION = 274


# ---------------------------------------------------------------------------
# Synthetic TIFF helpers
# ---------------------------------------------------------------------------


def _write_photoshop_tiff(
    path: Path,
    *,
    width: int = 4000,
    height: int = 3000,
    software: str = "Adobe Photoshop 24.6 (Windows)",
    make: str = "Canon",
    model: str = "Canon PowerShot S120",
    artist: str = EXPECTED_EXIF_ARTIST,
    copyright_: str = EXPECTED_EXIF_COPYRIGHT,
    orientation: int = 1,
) -> None:
    """Write a tiny TIFF matching ADR-0009 Finding B.

    Deliberately omits ExposureTime, FNumber, ISOSpeedRatings, FocalLength,
    DateTimeOriginal — Photoshop's TIFF export drops the Exif sub-IFD.
    """
    info = TiffImagePlugin.ImageFileDirectory_v2()
    if make:
        info[TAG_MAKE] = make
    if model:
        info[TAG_MODEL] = model
    if artist:
        info[TAG_ARTIST] = artist
    if copyright_:
        info[TAG_COPYRIGHT] = copyright_
    if software:
        info[TAG_SOFTWARE] = software
    if orientation:
        info[TAG_ORIENTATION] = orientation

    img = Image.new("RGB", (width, height), (60, 90, 120))
    img.save(path, format="TIFF", tiffinfo=info, compression="tiff_lzw")


# ---------------------------------------------------------------------------
# Synthetic IDS CSV helpers
# ---------------------------------------------------------------------------

_IDS_COLUMNS = [
    "id", "uuid", "image_id", "credit", "contact", "copyright",
    "usageterms", "imagedescription", "attribution_url",
    "event",           # always null
    "gpsareainformation", "gpsmapdatum",
    "pid",             # always null
    "dtoriginal", "dtmodified",
    "gpsdate",         # always null
    "gpstime",         # always null
    "lat", "latref", "lng", "lngref",
    "artist", "externalmetadata",
    "dtdigitized",     # always null
    "contributor",     # always null
    "preservedfilename", "cammake", "cammodel",
]

_NULL_COLS = {"event", "pid", "gpsdate", "gpstime", "dtdigitized", "contributor"}


def _csv_row(
    filename: str,
    image_id: int = 1,
    *,
    cammake: str = "Canon",
    cammodel: str = "Canon PowerShot S120",
    artist: str = EXPECTED_EXIF_ARTIST,
    copyright_: str = EXPECTED_EXIF_COPYRIGHT,
    dtoriginal: str = "2023-07-12 14:39:55+00:00",
    lat: float = 24.45913,
    lng: float = -81.84534,
) -> dict[str, Any]:
    row = {c: "" for c in _IDS_COLUMNS}
    row.update(
        id=image_id,
        uuid="32d24f1600254494b5722ea5d677d936",
        image_id=image_id,
        credit="U.S. Geological Survey",
        contact="gs-g-spcmsc_data_inquiries@usgs.gov",
        copyright=copyright_,
        usageterms="Public Domain usage terms",
        imagedescription="test image",
        attribution_url="https://doi.org/10.5066/P1WHKTRD",
        gpsareainformation="station coordinates obtained from handheld GPS",
        gpsmapdatum="EPSG:4326 (WGS 84)",
        dtoriginal=dtoriginal,
        dtmodified="2023-07-14 11:35:10+00:00",
        lat=lat,
        latref="N",
        lng=lng,
        lngref="W",
        artist=artist,
        externalmetadata="https://www1.usgs.gov/pir/api/identifiers/USGS:test",
        preservedfilename=filename,
        cammake=cammake,
        cammodel=cammodel,
    )
    # Null columns are empty strings — pandas will read them as NaN
    for col in _NULL_COLS:
        row[col] = ""
    return row


def _write_ids_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    with path.open("w", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=_IDS_COLUMNS)
        writer.writeheader()
        writer.writerows(rows)


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def edr_site(tmp_path: Path):
    """A minimal synthetic EDR site: 3 TIFFs + IDS CSV + manifest."""
    site_dir = tmp_path / "EasternDryRocks"
    site_dir.mkdir()

    names = [
        "20230711_EDR_T8_R6_000300.tif",
        "20230711_EDR_T8_R6_000301.tif",
        "20230711_EDR_T8_R6_000302.tif",
    ]
    for name in names:
        _write_photoshop_tiff(site_dir / name)

    ids_csv = tmp_path / "exif_data.csv"
    _write_ids_csv(
        ids_csv,
        [_csv_row(name, image_id=i + 1) for i, name in enumerate(names)],
    )

    manifest = tmp_path / "manifest.csv"
    with manifest.open("w") as fh:
        fh.write("url,name,size\n")
        for name in names:
            fh.write(f"https://example.usgs.gov/{name},{name},100000\n")

    return {
        "site_dir": site_dir,
        "ids_csv": ids_csv,
        "manifest": manifest,
        "names": names,
    }


# ---------------------------------------------------------------------------
# ids_csv loader
# ---------------------------------------------------------------------------


def test_load_ids_csv_round_trips(tmp_path: Path):
    csv_path = tmp_path / "exif_data.csv"
    _write_ids_csv(csv_path, [_csv_row("20230711_EDR_T8_R6_000300.tif", image_id=843464)])
    records = load_ids_csv(csv_path)
    assert "20230711_edr_t8_r6_000300.tif" in records
    rec = records["20230711_edr_t8_r6_000300.tif"]
    assert rec.image_id == 843464
    assert rec.cammake == "Canon"
    assert rec.cammodel == "Canon PowerShot S120"
    assert rec.dtoriginal == "2023-07-12 14:39:55+00:00"
    assert rec.lat == pytest.approx(24.45913)
    assert rec.lon == pytest.approx(-81.84534)


def test_load_ids_csv_null_cols_ignored(tmp_path: Path):
    csv_path = tmp_path / "exif_data.csv"
    _write_ids_csv(csv_path, [_csv_row("img.tif")])
    records = load_ids_csv(csv_path)
    assert len(records) == 1


# ---------------------------------------------------------------------------
# build_inventory with CSV join
# ---------------------------------------------------------------------------


def test_inventory_joins_csv(edr_site):
    ids_records = load_ids_csv(edr_site["ids_csv"])
    inv = build_inventory(
        edr_site["site_dir"],
        ids_records=ids_records,
        use_exiftool=False,
    )
    assert len(inv) == 3
    for rec in inv:
        assert rec.csv_matched is True
        assert rec.image_id is not None
        assert rec.csv_cammake == "Canon"
        assert rec.csv_cammodel == "Canon PowerShot S120"
        assert rec.csv_dtoriginal_utc == "2023-07-12 14:39:55+00:00"
        assert rec.csv_lat == pytest.approx(24.45913)


def test_inventory_csv_unmatched_when_no_ids(edr_site):
    inv = build_inventory(edr_site["site_dir"], use_exiftool=False)
    for rec in inv:
        assert rec.csv_matched is False
        assert rec.image_id is None


def test_inventory_reads_software_tag(edr_site):
    ids_records = load_ids_csv(edr_site["ids_csv"])
    inv = build_inventory(edr_site["site_dir"], ids_records=ids_records, use_exiftool=False)
    for rec in inv:
        assert rec.software is not None
        assert rec.software.startswith("Adobe Photoshop")


def test_inventory_reads_orientation(edr_site):
    ids_records = load_ids_csv(edr_site["ids_csv"])
    inv = build_inventory(edr_site["site_dir"], ids_records=ids_records, use_exiftool=False)
    for rec in inv:
        assert rec.orientation == 1


# ---------------------------------------------------------------------------
# validate_image — happy path
# ---------------------------------------------------------------------------


def test_happy_path_all_pass(edr_site):
    ids_records = load_ids_csv(edr_site["ids_csv"])
    inv = build_inventory(edr_site["site_dir"], ids_records=ids_records, use_exiftool=False)
    for rec in inv:
        findings = {f.code: f for f in validate_image(rec)}
        assert findings["csv_join"].is_pass
        assert findings["software_lineage"].is_pass
        assert findings["camera_consistency"].is_pass
        assert findings["dimensions"].is_pass
        assert findings["exif_artist"].is_pass
        assert findings["exif_copyright"].is_pass
        assert findings["datetime_original"].is_pass
        assert findings["gps_present"].is_pass


# ---------------------------------------------------------------------------
# validate_image — per-rule failure modes
# ---------------------------------------------------------------------------


def test_missing_file_not_in_inventory(edr_site):
    """A file in the manifest that's missing from disk won't appear in inventory."""
    ids_records = load_ids_csv(edr_site["ids_csv"])
    inv = build_inventory(edr_site["site_dir"], ids_records=ids_records, use_exiftool=False)
    on_disk = {r.name for r in inv}
    # Remove one file
    missing = edr_site["names"][0]
    (edr_site["site_dir"] / missing).unlink()
    inv2 = build_inventory(edr_site["site_dir"], ids_records=ids_records, use_exiftool=False)
    assert missing not in {r.name for r in inv2}
    assert len(inv2) == 2


def test_wrong_software_tag_fails(tmp_path: Path):
    site_dir = tmp_path / "EDR"
    site_dir.mkdir()
    _write_photoshop_tiff(site_dir / "img.tif", software="GIMP 2.10")
    inv = build_inventory(site_dir, use_exiftool=False)
    findings = {f.code: f for f in validate_image(inv[0])}
    assert findings["software_lineage"].is_fail
    assert "GIMP" in findings["software_lineage"].details.get("software", "")


def test_dimension_mismatch_fails(tmp_path: Path):
    site_dir = tmp_path / "EDR"
    site_dir.mkdir()
    _write_photoshop_tiff(site_dir / "img.tif", width=1920, height=1080)
    inv = build_inventory(site_dir, use_exiftool=False)
    findings = {f.code: f for f in validate_image(inv[0])}
    assert findings["dimensions"].is_fail


def test_missing_from_csv_fails(edr_site, tmp_path):
    """File on disk that has no row in the CSV → csv_join fail."""
    extra_file = edr_site["site_dir"] / "20230711_EDR_T8_R6_EXTRA.tif"
    _write_photoshop_tiff(extra_file)
    ids_records = load_ids_csv(edr_site["ids_csv"])
    inv = build_inventory(edr_site["site_dir"], ids_records=ids_records, use_exiftool=False)
    extra_recs = [r for r in inv if r.name == "20230711_EDR_T8_R6_EXTRA.tif"]
    assert len(extra_recs) == 1
    findings = {f.code: f for f in validate_image(extra_recs[0])}
    assert findings["csv_join"].is_fail


def test_size_mismatch_in_manifest(edr_site):
    """The manifest check captures when on-disk file size differs from manifest size."""
    # Write a manifest with wrong sizes
    manifest_path = edr_site["manifest"]
    names = edr_site["names"]
    with manifest_path.open("w") as fh:
        fh.write("url,name,size\n")
        for name in names:
            # Claim each file is 1 GB
            fh.write(f"https://example.usgs.gov/{name},{name},1073741824\n")
    # The inventory itself doesn't fail — the manifest check is surfaced in
    # extra_context by cmd_validate_intake.  Here we verify size_bytes is real.
    ids_records = load_ids_csv(edr_site["ids_csv"])
    inv = build_inventory(edr_site["site_dir"], ids_records=ids_records, use_exiftool=False)
    for rec in inv:
        assert rec.size_bytes < 1_073_741_824  # on-disk < claimed 1 GB


# ---------------------------------------------------------------------------
# validate_dataset — csv_coverage
# ---------------------------------------------------------------------------


def test_csv_coverage_all_matched(edr_site):
    ids_records = load_ids_csv(edr_site["ids_csv"])
    inv = build_inventory(edr_site["site_dir"], ids_records=ids_records, use_exiftool=False)
    findings = {f.code: f for f in validate_dataset(inv)}
    assert findings["csv_coverage"].is_pass


def test_csv_coverage_unmatched_warns_or_fails(edr_site):
    # No CSV → all csv_matched=False
    inv = build_inventory(edr_site["site_dir"], use_exiftool=False)
    findings = {f.code: f for f in validate_dataset(inv)}
    assert findings["csv_coverage"].severity in ("warn", "fail")


# ---------------------------------------------------------------------------
# CLI — strict mode exit code
# ---------------------------------------------------------------------------


def test_strict_mode_returns_nonzero_on_failure(edr_site, tmp_path):
    """--strict causes non-zero exit when overall_severity is fail."""
    out_dir = tmp_path / "out"
    out_dir.mkdir()

    # Write a TIFF with wrong software so software_lineage fails
    (edr_site["site_dir"] / edr_site["names"][0]).unlink()
    _write_photoshop_tiff(
        edr_site["site_dir"] / edr_site["names"][0], software="ImageMagick"
    )

    parser = build_parser()
    args = parser.parse_args([
        "validate-intake",
        str(edr_site["site_dir"]),
        "--ids-csv", str(edr_site["ids_csv"]),
        "--out-dir", str(out_dir),
        "--strict",
    ])
    from reef_sfm_provenance.__main__ import cmd_validate_intake
    rc = cmd_validate_intake(args)
    assert rc == 1


def test_default_mode_returns_zero_even_on_failure(edr_site, tmp_path):
    """Without --strict, exit code is 0 regardless of failures."""
    out_dir = tmp_path / "out"
    out_dir.mkdir()

    # Write a TIFF with wrong software
    (edr_site["site_dir"] / edr_site["names"][0]).unlink()
    _write_photoshop_tiff(
        edr_site["site_dir"] / edr_site["names"][0], software="ImageMagick"
    )

    parser = build_parser()
    args = parser.parse_args([
        "validate-intake",
        str(edr_site["site_dir"]),
        "--ids-csv", str(edr_site["ids_csv"]),
        "--out-dir", str(out_dir),
    ])
    from reef_sfm_provenance.__main__ import cmd_validate_intake
    rc = cmd_validate_intake(args)
    assert rc == 0


def test_output_artifacts_written(edr_site, tmp_path):
    """validate-intake always writes inventory.json, qc_report.json, qc_report.md."""
    out_dir = tmp_path / "out"
    out_dir.mkdir()
    parser = build_parser()
    args = parser.parse_args([
        "validate-intake",
        str(edr_site["site_dir"]),
        "--ids-csv", str(edr_site["ids_csv"]),
        "--out-dir", str(out_dir),
    ])
    from reef_sfm_provenance.__main__ import cmd_validate_intake
    cmd_validate_intake(args)

    assert (out_dir / "inventory.json").exists()
    assert (out_dir / "qc_report.json").exists()
    assert (out_dir / "qc_report.md").exists()

    report = json.loads((out_dir / "qc_report.json").read_text())
    assert report["schema"] == "reef-sfm-provenance/intake_qc/v2"
    assert report["image_count"] == 3
    assert report["csv_join_count"] == 3
    assert "metadata_lineage" in report
    assert "DateTimeOriginal" in report["metadata_lineage"]["fields_absent_by_design"]["missing_exif_tags"]
