# reef-sfm-mote-keys — shared bash helpers
#
# Sourced by every script in scripts/aws/. Provides:
#   - log_info / log_warn / log_error / log_step  : consistent output
#   - require_var                                 : fail fast on missing config
#   - ensure_aws_cli                              : confirm aws CLI is usable
#   - tag_args                                    : produce --tag-specifications for create-* calls
#   - persist_resource                            : append resource ID to docs/aws-resources.md
#   - record_step                                 : mark steps complete (idempotency anchor)
#
# Conventions:
#   - All AWS calls explicitly pass --region "$AWS_REGION".
#   - All AWS calls produce JSON; jq parses.
#   - Scripts exit non-zero on any AWS error (set -euo pipefail).

# -----------------------------------------------------------------------------
# Strict mode for all sourcing scripts
# -----------------------------------------------------------------------------
set -euo pipefail

# Color codes (only if stdout is a tty)
if [[ -t 1 ]]; then
    readonly C_RESET='\033[0m'
    readonly C_RED='\033[0;31m'
    readonly C_YELLOW='\033[0;33m'
    readonly C_GREEN='\033[0;32m'
    readonly C_BLUE='\033[0;34m'
    readonly C_BOLD='\033[1m'
else
    readonly C_RESET=''
    readonly C_RED=''
    readonly C_YELLOW=''
    readonly C_GREEN=''
    readonly C_BLUE=''
    readonly C_BOLD=''
fi

log_step()  { printf "${C_BOLD}${C_BLUE}==> %s${C_RESET}\n" "$*" >&2; }
log_info()  { printf "    %s\n" "$*" >&2; }
log_warn()  { printf "${C_YELLOW}    WARN: %s${C_RESET}\n" "$*" >&2; }
log_error() { printf "${C_RED}    ERROR: %s${C_RESET}\n" "$*" >&2; }
log_ok()    { printf "${C_GREEN}    OK: %s${C_RESET}\n" "$*" >&2; }

# require_var VAR_NAME [hint]
# Exits if the named variable is empty.
require_var() {
    local var_name="$1"
    local hint="${2:-edit config/aws-config.sh}"
    local value="${!var_name:-}"
    if [[ -z "$value" ]]; then
        log_error "Required variable \$${var_name} is not set."
        log_error "Hint: ${hint}"
        exit 1
    fi
}

# ensure_aws_cli
# Confirm aws CLI exists, credentials work, region is reachable.
ensure_aws_cli() {
    if ! command -v aws &> /dev/null; then
        log_error "aws CLI not found. On macOS: brew install awscli"
        exit 1
    fi
    if ! command -v jq &> /dev/null; then
        log_error "jq not found. On macOS: brew install jq"
        exit 1
    fi
    local caller_json
    if ! caller_json="$(aws sts get-caller-identity --region "$AWS_REGION" --output json 2>&1)"; then
        log_error "aws sts get-caller-identity failed:"
        log_error "$caller_json"
        log_error "Run: aws configure"
        exit 1
    fi
    local account user_arn
    account="$(echo "$caller_json" | jq -r '.Account')"
    user_arn="$(echo "$caller_json" | jq -r '.Arn')"
    log_info "AWS account: ${account}"
    log_info "AWS identity: ${user_arn}"
    log_info "AWS region: ${AWS_REGION}"
}

# tag_args RESOURCE_TYPE NAME
# Emits a --tag-specifications argument for aws ec2 create-* commands.
# Every resource we create gets Project= and Name= tags.
tag_args() {
    local resource_type="$1"
    local name="$2"
    printf 'ResourceType=%s,Tags=[{Key=Project,Value=%s},{Key=Name,Value=%s}]' \
        "$resource_type" "$PROJECT_TAG" "$name"
}

# persist_resource KEY VALUE
# Records a key=value pair in docs/aws-resources.md (creating the file if needed).
# Existing entries with the same key are replaced. Use this immediately after
# creating any AWS resource we'll want to find again later.
persist_resource() {
    local key="$1"
    local value="$2"
    local file="${RESOURCES_FILE}"
    mkdir -p "$(dirname "$file")"
    if [[ ! -f "$file" ]]; then
        cat > "$file" <<EOF
# AWS resources for reef-sfm-mote-keys

This file is generated by the scripts in \`scripts/aws/\`. It records resource
IDs created during AWS setup so later scripts (and you) can find them.

DO NOT EDIT MANUALLY — re-run the relevant script if a value is wrong.

This file is gitignored by default. The IDs aren't secret, but they're not
useful to anyone else and clutter git history.

## Resources

EOF
    fi
    # Replace existing line if present, else append
    if grep -q "^- ${key}: " "$file" 2>/dev/null; then
        # Use a temp file to avoid in-place sed portability issues between macOS/Linux
        local tmp
        tmp="$(mktemp)"
        sed "s|^- ${key}: .*|- ${key}: \`${value}\`|" "$file" > "$tmp"
        mv "$tmp" "$file"
    else
        echo "- ${key}: \`${value}\`" >> "$file"
    fi
    log_ok "Recorded ${key} = ${value}"
}

# read_resource KEY
# Reads a value back from docs/aws-resources.md. Empty string if not found.
read_resource() {
    local key="$1"
    local file="${RESOURCES_FILE}"
    [[ -f "$file" ]] || { echo ""; return 0; }
    grep "^- ${key}: " "$file" 2>/dev/null | sed -E "s|^- ${key}: \`([^\`]*)\`.*|\1|" | head -n1 || echo ""
}

# wait_for_state RESOURCE_TYPE RESOURCE_ID DESIRED_STATE
# Polls until the given EC2 resource reaches the desired state. Times out
# after ~5 minutes. Supports: instance, volume.
wait_for_state() {
    local resource_type="$1"
    local resource_id="$2"
    local desired_state="$3"
    local max_attempts=60   # 60 * 5s = 5 minutes
    local attempt=0
    log_info "Waiting for ${resource_type} ${resource_id} -> ${desired_state}..."
    while (( attempt < max_attempts )); do
        local current_state
        case "$resource_type" in
            instance)
                current_state="$(aws ec2 describe-instances \
                    --instance-ids "$resource_id" \
                    --region "$AWS_REGION" \
                    --query 'Reservations[0].Instances[0].State.Name' \
                    --output text 2>/dev/null || echo "unknown")"
                ;;
            volume)
                current_state="$(aws ec2 describe-volumes \
                    --volume-ids "$resource_id" \
                    --region "$AWS_REGION" \
                    --query 'Volumes[0].State' \
                    --output text 2>/dev/null || echo "unknown")"
                ;;
            *)
                log_error "wait_for_state: unsupported resource type ${resource_type}"
                return 1
                ;;
        esac
        if [[ "$current_state" == "$desired_state" ]]; then
            log_ok "${resource_type} ${resource_id} is ${desired_state}"
            return 0
        fi
        sleep 5
        attempt=$((attempt + 1))
    done
    log_error "Timed out waiting for ${resource_type} ${resource_id} to reach ${desired_state}"
    return 1
}
